before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
